openapi: 3.0.0
tags:
  name: Categorias
  description: API para interactura con las categorias
paths:
  /category:
    get:
      summary: Muestra las categorias disponibles
      tags: [Categoria]
      parameters:
        - in: header
          name: token
          type: string
      responses:
        200:
          description: Regresa las categorias registradas
    post:
      summary: Registra una categoria
      tags: [Categoria]
      parameters:
        - in: header
          name: token
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/categoria'
      responses:
        200:
          description: Categoria registrada
    delete:
      summary: Elimina una categoria
      tags: [Categoria]
      parameters:
        - in: header
          name: token
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/categoria'
      responses:
        200:
          description: Categoria eliminada
components:
  schemas:
    postCategoria:
      type: object
      properties:
        name:
          type: string
          description: Nombre de la categoria
        description:
          type: string
          description: Descripcion de la categoria
    deleteCategoria:
      type: object
      properties:
        id:
          type: string
          description: Id de la categoria