openapi: 3.0.0
tags:
  name: Productos
  description: API para interactura con los productos
paths:
  /categorias:
    get:
      summary: Muestra las categorias disponibles
      tags: [Product]
      parameters:
        - in: header
          name: token
          type: string
      responses:
        200:
          description: Regresa las productos registrados
    post:
      summary: Registra un producto
      tags: [Product]
      parameters:
        - in: header
          name: token
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postCategorya'
      responses:
        200:
          description: producto registrado
    
                
    delete:
      summary: Elimina un producto
      tags: [Product]
      parameters:
        - in: header
          name: token
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteCategorya'
      responses:
        200:
          description: Producto eliminada
  /product?id=:
    get:
      summary: Muestra un producto por id
      tags: [Product]
      parameters:
        - in: header
          name: token
          type: string
      responses:
        description: Muestra un producto
components:
  schemas:
    deleteCategorya:
      type: object
      properties:
        id:
          type: string
          description: Id de la categoria