openapi: 3.0.0
tags:
  name: Productos
  description: API para interactura con los productos
paths:
  /productos:
    get:
      summary: Muestra las productos disponibles
      tags: [Product]
      parameters:
        - in: header
          name: token
          type: string
      responses:
        200:
          description: Regresa las productos registrados
    post:
      summary: Registra un producto
      tags: [Product]
      parameters:
        - in: header
          name: token
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postCategorya'
      responses:
        200:
          description: producto registrado
    
                
    
  /categoria/{id}:
    get:
      tags: [Product]
      summary: "elimine la categoria"
      description: "\n<p>This API endpoint allows you to delete a consignee.</p>\n"
      operationId: "delete_consignees_id"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "400":
          description: "Bad Request."
          content: {}
        "404":
          description: "Not Found."
          content: {}
        "500":
          description: "Internal Server Error."
          content: {}
    delete:
      tags: [Product]
      summary: "elimine la categoria"
      description: "\n<p>This API endpoint allows you to delete a consignee.</p>\n"
      operationId: "delete_consignees_id"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "400":
          description: "Bad Request."
          content: {}
        "404":
          description: "Not Found."
          content: {}
        "500":
          description: "Internal Server Error."
          content: {}
components:
  schemas:
    deleteCategorya:
      type: object
      properties:
        id:
          type: string
          description: Id de Producto